services:
  elasticsearchcrud:
    image: ${DOCKER_REGISTRY-}elasticsearchcrud
    build:
      context: .
      dockerfile: ElasticSearchCRUD/Dockerfile
    networks:
      - elasticnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - C:\esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticnet

networks:
  elasticnet:
    driver: bridge
